import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import { EmailHeader } from './WelcomeEmail'

export interface ContactNotificationProps {
  name: string
  email: string
  phone?: string | null
  subject: string
  message: string
  submittedAt: string
}

export function ContactNotification({
  name,
  email,
  phone,
  subject,
  message,
  submittedAt,
}: ContactNotificationProps) {
  const dt = new Date(submittedAt).toLocaleString('en-US', {
    timeZone: 'America/New_York',
    dateStyle: 'full',
    timeStyle: 'short',
  })

  return (
    <Html>
      <Head />
      <Preview>[NEW CONTACT] {subject} — {name}</Preview>
      <Body style={body}>
        <Container style={container}>
          <EmailHeader />

          <Section style={content}>
            <Row label="姓名 / Name" value={name} />
            <Row label="邮箱 / Email" value={email} />
            <Row label="电话 / Phone" value={phone || 'Not provided'} />
            <Row label="主题 / Subject" value={subject} />
            <Row label="提交时间 / Submitted" value={dt} />

            <Hr style={hr} />

            <Text style={fieldLabel}>留言 / Message</Text>
            <Section style={messageBox}>
              <Text style={messageText}>{message}</Text>
            </Section>

            <Hr style={hr} />
            <Text style={footer}>
              This notification was automatically generated by the Charlotte Chinese Academy
              registration portal. Reply to this email is not monitored — log in to the admin
              portal to manage this message.
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  )
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <Section style={{ marginBottom: 8 }}>
      <Text style={fieldLabel}>{label}</Text>
      <Text style={fieldValue}>{value}</Text>
    </Section>
  )
}

const body: React.CSSProperties = {
  backgroundColor: '#f9fafb',
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  margin: 0,
  padding: '32px 0',
}
const container: React.CSSProperties = {
  backgroundColor: '#ffffff',
  borderRadius: 8,
  border: '1px solid #e5e7eb',
  margin: '0 auto',
  maxWidth: 560,
  overflow: 'hidden',
}
const content: React.CSSProperties = { padding: '24px 32px' }
const fieldLabel: React.CSSProperties = {
  color: '#6b7280', fontSize: 11, fontWeight: 600, textTransform: 'uppercase',
  letterSpacing: '0.05em', margin: '0 0 2px',
}
const fieldValue: React.CSSProperties = {
  color: '#111827', fontSize: 14, margin: '0 0 4px',
}
const messageBox: React.CSSProperties = {
  backgroundColor: '#f9fafb',
  border: '1px solid #e5e7eb',
  borderRadius: 6,
  padding: '12px 16px',
  margin: '8px 0 0',
}
const messageText: React.CSSProperties = {
  color: '#374151', fontSize: 14, lineHeight: 1.6, margin: 0, whiteSpace: 'pre-wrap',
}
const hr: React.CSSProperties = { borderColor: '#e5e7eb', margin: '16px 0' }
const footer: React.CSSProperties = {
  color: '#9ca3af', fontSize: 11, lineHeight: 1.5, margin: 0,
}
